#nome = input('qual o seu nome? ')
#print(f'O seu nome é {nome}')
numero_1 = int(input('Digite um número: '))
numero_2 = int(input('digite outro numero: '))
print(f'a soma do numeros é: {numero_1 + numero_2}')
